---
  12: { name: "Rosy Cheeks", gender: "male" }
  13: { name: "Luxurious Beard", gender: "male" }
  14: { name: "Clown Hair Green", gender: "male" }
  15: { name: "Mohawk Dark", gender: "male" }
  16: { name: "Cowboy Hat", gender: "male" }
  17: { name: "Mustache", gender: "male" }
  18: { name: "Clown Nose", gender: "male" }
  19: { name: "Cigarette", gender: "male" }
  20: { name: "Nerd Glasses", gender: "male" }
  21: { name: "Regular Shades", gender: "male" }
  22: { name: "Knitted Cap", gender: "male" }
  23: { name: "Shadow Beard", gender: "male" }
  24: { name: "Frown", gender: "male" }
  25: { name: "Cap Forward", gender: "male" }
  26: { name: "Goat", gender: "male" }
  27: { name: "Mole", gender: "male" }
  28: { name: "Purple Hair", gender: "male" }
  29: { name: "Small Shades", gender: "male" }
  30: { name: "Shaved Head", gender: "male" }
  31: { name: "Classic Shades", gender: "male" }
  32: { name: "Vape", gender: "male" }
  33: { name: "Silver Chain", gender: "male" }
  34: { name: "Smile", gender: "male" }
  35: { name: "Big Shades", gender: "male" }
  36: { name: "Mohawk Thin", gender: "male" }
  37: { name: "Beanie", gender: "male" }
  38: { name: "Cap", gender: "male" }
  39: { name: "Clown Eyes Green", gender: "male" }
  40: { name: "Normal Beard Black", gender: "male" }
  41: { name: "Medical Mask", gender: "male" }
  42: { name: "Normal Beard", gender: "male" }
  43: { name: "VR", gender: "male" }
  44: { name: "Eye Patch", gender: "male" }
  45: { name: "Wild Hair", gender: "male" }
  46: { name: "Top Hat", gender: "male" }
  47: { name: "Bandana", gender: "male" }
  48: { name: "Handlebars", gender: "male" }
  49: { name: "Frumpy Hair", gender: "male" }
  50: { name: "Crazy Hair", gender: "male" }
  51: { name: "Police Cap", gender: "male" }
  52: { name: "Buck Teeth", gender: "male" }
  53: { name: "Do-rag", gender: "male" }
  54: { name: "Front Beard", gender: "male" }
  55: { name: "Spots", gender: "male" }
  56: { name: "Big Beard", gender: "male" }
  57: { name: "Vampire Hair", gender: "male" }
  58: { name: "Peak Spike", gender: "male" }
  59: { name: "Chinstrap", gender: "male" }
  60: { name: "Fedora", gender: "male" }
  61: { name: "Earring", gender: "male" }
  62: { name: "Horned Rim Glasses", gender: "male" }
  63: { name: "Headband", gender: "male" }
  64: { name: "Pipe", gender: "male" }
  65: { name: "Messy Hair", gender: "male" }
  66: { name: "Front Beard Dark", gender: "male" }
  67: { name: "Hoodie", gender: "male" }
  68: { name: "Gold Chain", gender: "male" }
  69: { name: "Muttonchops", gender: "male" }
  70: { name: "Stringy Hair", gender: "male" }
  71: { name: "Eye Mask", gender: "male" }
  72: { name: "3D Glasses", gender: "male" }
  73: { name: "Clown Eyes Blue", gender: "male" }
  74: { name: "Mohawk", gender: "male" }
  75: { name: "Pilot Helmet", gender: "female" }
  76: { name: "Tassle Hat", gender: "female" }
  77: { name: "Hot Lipstick", gender: "female" }
  78: { name: "Blue Eye Shadow", gender: "female" }
  79: { name: "Straight Hair Dark", gender: "female" }
  80: { name: "Choker", gender: "female" }
  81: { name: "Crazy Hair", gender: "female" }
  82: { name: "Regular Shades", gender: "female" }
  83: { name: "Wild Blonde", gender: "female" }
  84: { name: "3D Glasses", gender: "female" }
  85: { name: "Mole", gender: "female" }
  86: { name: "Wild White Hair", gender: "female" }
  87: { name: "Spots", gender: "female" }
  88: { name: "Frumpy Hair", gender: "female" }
  89: { name: "Nerd Glasses", gender: "female" }
  90: { name: "Tiara", gender: "female" }
  91: { name: "Orange Side", gender: "female" }
  92: { name: "Red Mohawk", gender: "female" }
  93: { name: "Messy Hair", gender: "female" }
  94: { name: "Clown Eyes Blue", gender: "female" }
  95: { name: "Pipe", gender: "female" }
  96: { name: "Wild Hair", gender: "female" }
  97: { name: "Purple Eye Shadow", gender: "female" }
  98: { name: "Stringy Hair", gender: "female" }
  99: { name: "Dark Hair", gender: "female" }
  100: { name: "Eye Patch", gender: "female" }
  101: { name: "Blonde Short", gender: "female" }
  102: { name: "Classic Shades", gender: "female" }
  103: { name: "Eye Mask", gender: "female" }
  104: { name: "Clown Hair Green", gender: "female" }
  105: { name: "Cap", gender: "female" }
  106: { name: "Medical Mask", gender: "female" }
  107: { name: "Bandana", gender: "female" }
  108: { name: "Purple Lipstick", gender: "female" }
  109: { name: "Clown Nose", gender: "female" }
  110: { name: "Headband", gender: "female" }
  111: { name: "Pigtails", gender: "female" }
  112: { name: "Straight Hair Blonde", gender: "female" }
  113: { name: "Knitted Cap", gender: "female" }
  114: { name: "Clown Eyes Green", gender: "female" }
  115: { name: "Cigarette", gender: "female" }
  116: { name: "Welding Goggles", gender: "female" }
  117: { name: "Mohawk Thin", gender: "female" }
  118: { name: "Gold Chain", gender: "female" }
  119: { name: "VR", gender: "female" }
  120: { name: "Vape", gender: "female" }
  121: { name: "Pink With Hat", gender: "female" }
  122: { name: "Blonde Bob", gender: "female" }
  123: { name: "Mohawk", gender: "female" }
  124: { name: "Big Shades", gender: "female" }
  125: { name: "Earring", gender: "female" }
  126: { name: "Green Eye Shadow", gender: "female" }
  127: { name: "Straight Hair", gender: "female" }
  128: { name: "Rosy Cheeks", gender: "female" }
  129: { name: "Half Shaved", gender: "female" }
  130: { name: "Mohawk Dark", gender: "female" }
  131: { name: "Black Lipstick", gender: "female" }
  132: { name: "Horned Rim Glasses", gender: "female" }
  133: { name: "Silver Chain", gender: "female" }